//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_DoKhacViet_2210900137.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_GIA
    {
        public int Ma_danh_gia { get; set; }
        public Nullable<int> Ma_thanh_vien { get; set; }
        public Nullable<int> Ma_hinh_nen { get; set; }
        public Nullable<byte> So_sao_danh_gia { get; set; }
    
        public virtual HINH_NEN HINH_NEN { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
