//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_DoKhacViet_2210900137.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINH_NEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HINH_NEN()
        {
            this.DANH_GIA = new HashSet<DANH_GIA>();
        }
    
        public int Ma_hinh_nen { get; set; }
        public string Ten_hinh_nen { get; set; }
        public string Do_phan_giai_hinh_nen { get; set; }
        public Nullable<int> Kich_thuoc_file { get; set; }
        public string Ma_nguoi_tai_len { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANH_GIA> DANH_GIA { get; set; }
        public virtual QUAN_TRI QUAN_TRI { get; set; }
    }
}
