//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_DoKhacViet_2210900137.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUAN_TRI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUAN_TRI()
        {
            this.HINH_NEN = new HashSet<HINH_NEN>();
        }
    
        public string Tai_khoan { get; set; }
        public string Mat_khau { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINH_NEN> HINH_NEN { get; set; }
    }
}
